"""Score PaperTrail's verdicts against the hand-labeled answer key.

Usage:
  uv run python scripts/evaluate.py --ingest        # download+ingest paper & repo, then score
  uv run python scripts/evaluate.py                 # score using already-ingested data
  uv run python scripts/evaluate.py --no-follow-refs # skip reference-following (fewer API calls)
  uv run python scripts/evaluate.py --out eval/results.md --title "Reference case"  # write a table
"""

from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

import yaml

from paper_to_code.config import get_settings
from paper_to_code.models import Direction
from paper_to_code.service import PaperTrail

# Verdict explanations contain math symbols (Θ, √, …); force UTF-8 so printing them
# never crashes on a Windows cp1252 console.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

KEY_PATH = Path(__file__).resolve().parent.parent / "eval" / "answer_key.yaml"


def _download(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": "PaperTrail/0.1"})
    with urllib.request.urlopen(req) as resp, dest.open("wb") as fh:
        fh.write(resp.read())


def _write_results(out: Path, title: str, key: dict, counts: dict, rows: list[dict], passed: int) -> None:
    """Write (or append) a Markdown results section — a committable proof artifact."""
    lines: list[str] = []
    if not out.exists():
        lines += [
            "# Evaluation results",
            "",
            "Generated by `scripts/evaluate.py`, scoring PaperTrail's verdicts against the "
            "hand-labeled answer keys in `eval/`. Each case checks the verdict label (and, where "
            "relevant, that the cited code symbol matches). Run at temperature 0, so results are "
            "reproducible.",
            "",
        ]
    lines += [
        f"## {title}",
        "",
        f"Paper **{key['paper']['id']}** + repo **{key['code']['id']}** — "
        f"indexed {counts['paper_chunks']} paper chunks · {counts['code_chunks']} code chunks.",
        "",
        "| # | Question | Direction | Expected | Verdict | Conf | Code symbol | Result |",
        "| - | -------- | --------- | -------- | ------- | ---- | ----------- | ------ |",
    ]
    for i, r in enumerate(rows, 1):
        expected = " / ".join(r["expected"])
        symbol = r["cited"] or r["want_symbol"] or "—"
        result = "✅ PASS" if r["ok"] else "❌ FAIL"
        lines.append(
            f"| {i} | {r['question']} | {r['direction']} | {expected} | "
            f"`{r['verdict']}` | {r['conf']:.2f} | {symbol} | {result} |"
        )
    lines += ["", f"**Score: {passed}/{len(rows)}**", ""]
    with out.open("a", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ingest", action="store_true", help="Download + ingest paper and repo first.")
    parser.add_argument("--no-follow-refs", dest="follow_refs", action="store_false")
    parser.add_argument("--key", default=str(KEY_PATH), help="Path to the answer-key YAML.")
    parser.add_argument("--out", default=None, help="Write a Markdown results table to this path.")
    parser.add_argument("--title", default="Reference case", help="Section title for the results table.")
    args = parser.parse_args()

    key = yaml.safe_load(Path(args.key).read_text(encoding="utf-8"))
    paper_id = key["paper"]["id"]
    repo_id = key["code"]["id"]
    settings = get_settings()
    service = PaperTrail(settings)

    if args.ingest:
        pdf = Path(settings.papers_dir) / f"{paper_id}.pdf"
        if not pdf.exists():
            print(f"Downloading paper -> {pdf}")
            _download(key["paper"]["pdf_url"], pdf)
        print("Ingesting paper…")
        pr = service.ingest_paper(pdf, paper_id)
        print(f"  {len(pr.chunks)} paper chunks")
        print("Ingesting code…")
        cr = service.ingest_code(key["code"]["repo_url"], repo_id)
        print(f"  {len(cr.chunks)} code chunks")

    print(f"\nIndexed: {service.counts()}")
    print(f"Scoring against paper '{paper_id}' + repo '{repo_id}' (retrieval scoped to this pair)\n")

    passed = 0
    rows: list[dict] = []
    for case in key["cases"]:
        # Scope retrieval to this answer key's pair so other ingested papers can't leak in.
        result = service.ask(
            case["question"],
            direction=Direction(case["direction"]),
            follow_refs=args.follow_refs,
            paper_id=paper_id,
            repo_id=repo_id,
        )
        verdict = result.verdict
        verdict_ok = verdict.verdict.value in case["expected_verdicts"]

        want_symbol = case.get("expect_code_symbol")
        if want_symbol:
            seen = [h.chunk.metadata.get("symbol", "") for h in result.code_evidence]
            if verdict.code_citation:
                seen.append(verdict.code_citation.symbol or "")
            symbol_ok = any(want_symbol in (s or "") for s in seen)
        else:
            symbol_ok = True

        ok = verdict_ok and symbol_ok
        passed += int(ok)
        cited = verdict.code_citation.symbol if verdict.code_citation else None
        rows.append(
            {
                "question": case["question"],
                "direction": case["direction"],
                "expected": case["expected_verdicts"],
                "verdict": verdict.verdict.value,
                "conf": verdict.confidence,
                "want_symbol": want_symbol,
                "cited": cited,
                "ok": ok,
            }
        )
        print(f"[{'PASS' if ok else 'FAIL'}] {case['question']}")
        print(f"       verdict={verdict.verdict.value} expected={case['expected_verdicts']} (ok={verdict_ok})")
        print(f"       expect_symbol={want_symbol} cited={cited} (ok={symbol_ok}) conf={verdict.confidence:.2f}")
        print(f"       {verdict.explanation[:160]}")
        print()

    print(f"Score: {passed}/{len(key['cases'])}")

    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        _write_results(out, args.title, key, service.counts(), rows, passed)
        print(f"Wrote results table -> {out}")

    return 0 if passed == len(key["cases"]) else 1


if __name__ == "__main__":
    raise SystemExit(main())
